### ISSUE TITLE
Jupyter Troubleshooting

### ISSUE THREAD

**Issue by s-knapp** [kpegion/Pangeo-at-AOES#7]
On the Jupyter setup page, the recommended code in the troubleshooting section:

 jupyter lab --no-browser --ip=`hostname` --port=8878

is wrong. What worked for me was:

jupyter lab --no-browser --ip=`0.0.0.0` --port=8878

**Comment by kpegion** [comment]
Thanks @s-knapp.  I updated with the correct information.
